version: '3.7'
services:
  gerocuidado-forum-api:
    image: gerocuidadodev/node:18.17.0-alpine-dev
    container_name: gerocuidado-forum-api
    volumes:
      - '.:/home/node/app'
      - './.docker/entrypoint.sh:/home/node/app/.docker/entrypoint.sh'
    entrypoint: /home/node/app/.docker/entrypoint.sh
    environment:
      - NODE_ENV=development
    ports:
      - '3002:3002'
      - '7002:7002'
    depends_on:
      - gerocuidado-forum-db
    networks:
      - gerocuidado-forum-net
      - gerocuidado-apis-net

  gerocuidado-forum-db:
    build:
      context: ./.docker/postgres
      dockerfile: Dockerfile
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    container_name: gerocuidado-forum-db
    user: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - './.docker/postgres/config/postgresql.conf:/etc/postgresql/postgresql.conf'
    environment:
      - POSTGRES_DB=gerocuidado-forum-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5002:5002'
    networks:
      - gerocuidado-forum-net

networks:
  gerocuidado-forum-net:
    driver: bridge
  gerocuidado-apis-net:
    name: gerocuidado-apis-net
    external: true

volumes:
  pgdata:
